# Finding Symbols


Finding the ticker symbol, security identifier, the sector, and other metadata is easy if you know where to look.  This guide is intended to introduce some methods for searching, screening, and discovery.

For maximum coverage and functionality, install OpenBB with `[all]` packages.

The examples here will assume that the OpenBB Platform has been installed, the environment is active, and it has been imported into a Python session.  If the installation is fresh, or an extension was just installed, the Python interface will need to be rebuilt.  It will only take a few moments to complete.

In [1]:
from openbb import obb

The simplest way to find tickers is with a basic text query.

## Search Nasdaq

In [2]:
obb.equity.search("JPMorgan", provider="nasdaq").to_df().head(3)

,symbol,name,nasdaq_traded,exchange,etf,round_lot_size,test_issue,cqs_symbol,nasdaq_symbol,next_shares,market_category,financial_status
0,AMJB,JPMorgan Chase & Co. Alerian MLP Index ETNs du...,Y,P,Y,100.0,N,AMJB,AMJB,N,NaN,NaN
1,BBAG,JPMorgan BetaBuilders U.S. Aggregate Bond ETF,Y,P,Y,100.0,N,BBAG,BBAG,N,NaN,NaN
2,BBAX,JPMorgan BetaBuilders Developed Asia Pacific-e...,Y,Z,Y,100.0,N,BBAX,BBAX,N,NaN,NaN

## Search Cboe

In [3]:
obb.index.search("SPX", provider="cboe").to_df().tail(5)

,symbol,name,description,data_delay,currency,time_zone,open_time,close_time,tick_days,tick_frequency,tick_period,display_override_auto_hide,show_intraday_chart
31,SPXUIV,PROSHARES ULTRAPRO SHORT SP500 ETF,PROSHARES ULTRAPRO SHORT SP500 ETF\n,15,USD,America/Chicago,08:00:00,16:00:00,MonToFri,C,Regular,False,True
32,SPXVIV,PROSHARES S&P 500 EX-HEALTH CARE ETF,PROSHARES S&P 500 EX-HEALTH CARE ETF,15,USD,America/Chicago,08:00:00,16:00:00,MonToFri,C,Regular,False,True
33,VIX1D,Cboe 1-Day Volatility Index®,Estimates expected volatility by aggregating t...,15,USD,America/Chicago,08:00:00,16:00:00,MonToFri,C,Regular,False,True
34,VIX3M,Cboe S&P 500 3 Month Volatility Index,The Cboe 3-Month Volatility Index (VIX3M) is d...,15,USD,America/Chicago,08:00:00,16:00:00,MonToFri,C,Regular,False,True
35,WPUT,Cboe S&P 500 One-Week PutWrite Index,Tracks the value of a portfolio that overlays ...,15,USD,America/Chicago,08:00:00,16:00:00,MonToFri,C,Regular,False,True

## Search ETFs

In [5]:
obb.etf.search("gold", provider="tmx").to_df().iloc[-5:]

,symbol,name,short_name,inception_date,issuer,investment_style,esg,currency,unit_price,close,...,beta_3y,return_5y,return_10y,beta_10y,beta_15y,mer,dividend_frequency,pe_ratio,pb_ratio,beta_20y
21,ZGD,BMO Equal Weight Global Gold Index ETF,ZGD:CA,2012-11-14,BMO ETF,Mid Cap Blend,False,CAD,104.80,106.56,...,0.658557,0.130072,-0.079531,0.444583,NaN,0.0062,Annually,9.0939,0.8812,NaN
22,ZGLD,BMO Gold Bullion ETF,ZGLD:CA,2024-03-08,BMO ETF,Gold,False,CAD,36.83,36.83,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,ZGLD.U,BMO Gold Bullion ETF,ZGLD.U:CA,2024-03-08,BMO ETF,Gold,False,USD,36.05,36.70,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,ZGLH,BMO Gold Bullion Hedged to CAD ETF,ZGLH:CA,2024-03-08,BMO ETF,Gold,False,CAD,34.04,35.77,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,ZJG,BMO Junior Gold Index ETF,ZJG:CA,2010-01-19,BMO ETF,Small Cap Blend,True,CAD,92.75,92.84,...,0.641448,0.087857,-0.111992,0.449994,NaN,0.0061,Annually,13.5959,0.9830,NaN

In [6]:
obb.etf.search("covered call", provider="fmp").to_df().iloc[:5]

,symbol,name,market_cap,sector,industry,beta,price,last_annual_dividend,volume,exchange,exchange_name,country,actively_trading,isFund
0,QYLD,Global X NASDAQ 100 Covered Call ETF,8.197931e+09,Financial Services,Asset Management - Global,0.65,17.7950,2.05994,5225008.0,NASDAQ,NASDAQ Global Market,US,True,False
1,ZWB.TO,BMO Covered Call Canadian Banks ETF,2.988597e+09,Financial Services,Asset Management,0.96,18.2600,1.32000,88508.0,TSX,Toronto Stock Exchange,CA,True,False
2,XYLD,Global X S&P 500 Covered Call ETF,2.885254e+09,Financial Services,Asset Management - Global,0.51,40.9825,3.82220,157906.0,AMEX,New York Stock Exchange Arca,US,True,False
3,ZWU.TO,BMO Covered Call Utilities ETF,1.863225e+09,Financial Services,Asset Management,0.62,10.7900,0.84000,58903.0,TSX,Toronto Stock Exchange,CA,True,False
4,ZWC.TO,BMO CA High Dividend Covered Call ETF,1.637541e+09,Financial Services,Asset Management,0.89,17.6200,1.54000,22081.0,TSX,Toronto Stock Exchange,CA,True,False

## Search the SEC

Use an empty string, `""`, to return the complete list - over 10,000.

The SEC sorts this list by market cap.  Applying the `to_df()` method to `all_companies` will show them from biggest-to-smallest.

In [8]:
all_companies = obb.equity.search("", provider="sec")

print(len(all_companies.results))

all_companies.to_df().head(10)

10551

  symbol                                       name      cik
0   MSFT                             MICROSOFT CORP   789019
1   AAPL                                 Apple Inc.   320193
2  GOOGL                              Alphabet Inc.  1652044
3   NVDA                                NVIDIA CORP  1045810
4   AMZN                             AMAZON COM INC  1018724
5   META                       Meta Platforms, Inc.  1326801
6  BRK-B                     BERKSHIRE HATHAWAY INC  1067983
7    LLY                             ELI LILLY & Co    59478
8    TSM  TAIWAN SEMICONDUCTOR MANUFACTURING CO LTD  1046179
9   AVGO                              Broadcom Inc.  1730168

### Find an Institution

Some reporting companies, like invesment trusts and insurance companies, do not have a ticker symbol directly associated with them.  Filers in the US will have a CIK number, used to retrieve documents from the SEC.

In [9]:
instututions = obb.regulators.sec.institutions_search("Berkshire Hathaway").to_df()
instututions

                                               name         cik
0                      BERKSHIRE HATHAWAY ENERGY CO  0001081316
1                   BERKSHIRE HATHAWAY FINANCE CORP  0001274791
2        BERKSHIRE HATHAWAY HOMESTATE INSURANCE CO.  0000829771
3                       BERKSHIRE HATHAWAY INC /DE/  0000109694
4                         BERKSHIRE HATHAWAY INC/DE  0000109694
5                            BERKSHIRE HATHAWAY INC  0001067983
6  BERKSHIRE HATHAWAY LIFE INSURANCE CO OF NEBRASKA  0001015867
7                       LMZ & BERKSHIRE HATHAWAY CO  0001652795

### Find a Filing

Search for filings by CIK or ticker symbol.

In [10]:
homestate_filings = obb.equity.fundamental.filings(cik="0000829771", provider="sec")

homestate_filings.to_df().iloc[-1]

filing_date                                                       2003-02-14
accepted_date                                            2003-02-14 00:00:00
report_type                                                           13F-NT
filing_url                 https://www.sec.gov/Archives/edgar/data/000082...
report_url                 https://www.sec.gov/Archives/edgar/data/000082...
report_date                                                       2002-12-31
act
items
primary_doc_description                 FORM 13F-NT, PERIOD ENDED 12/31/2002
primary_doc                                              a87269a7e13fvnt.txt
accession_number                                        0000950150-03-000213
file_number                                                        028-02226
film_number                                                         03565329
is_inline_xbrl                                                             0
is_xbrl                                                                    0
size                                                                    4246
complete_submission_url    https://www.sec.gov/Archives/edgar/data/000082...
Name: 84, dtype: object

Or, search by form type.

In [12]:
aapl_filings = obb.equity.fundamental.filings("AAPL", type="4", provider="sec")

aapl_filings.to_df().iloc[0]

filing_date                                                       2024-01-11
accepted_date                                            2024-01-11 00:00:00
report_type                                                          DEF 14A
filing_url                 https://www.sec.gov/Archives/edgar/data/000032...
report_url                 https://www.sec.gov/Archives/edgar/data/000032...
report_date                                                       2024-02-28
act                                                                       34
items
primary_doc_description                                 APPLE INC. - DEF 14A
primary_doc                                             laapl2024_def14a.htm
accession_number                                        0001308179-24-000010
file_number                                                        001-36743
film_number                                                         24529569
is_inline_xbrl                                                             1
is_xbrl                                                                    1
size                                                                 9051163
complete_submission_url    https://www.sec.gov/Archives/edgar/data/000032...
Name: 0, dtype: object

## Screen Markets

Screeners provide a targeted search, a tool for comparison and discovery.  Find stocks from around the world with the screener endpoint, and the `openbb-fmp` provider.

### Find Stocks From India

In [7]:
results = obb.equity.screener(country="IN", provider="fmp").to_df()
display(len(results))
results.head(5).convert_dtypes()

5662

,symbol,name,market_cap,sector,industry,beta,price,last_annual_dividend,volume,exchange,exchange_name,country,is_etf,actively_trading,isFund
0,RELIANCE.NS,Reliance Industries Limited,20273316637500,Energy,Oil & Gas Refining & Marketing,0.631,2996.25,10.0,5222236,NSE,National Stock Exchange of India,IN,False,True,False
1,RELIANCE.BO,Reliance Industries Limited,20265535473000,Energy,Oil & Gas Refining & Marketing,0.631,2995.1,10.0,193482,BSE,Bombay Stock Exchange,IN,False,True,False
2,TCS.NS,Tata Consultancy Services Limited,16288641180000,Technology,Information Technology Services,0.531,4502.0,56.0,1829132,NSE,National Stock Exchange of India,IN,False,True,False
3,TCS.BO,Tata Consultancy Services Limited,16281224095500,Technology,Information Technology Services,0.531,4499.95,56.0,81625,BSE,Bombay Stock Exchange,IN,False,True,False
4,HDFCBANK.NS,HDFC Bank Limited,12426411437000,Financial Services,Banks - Regional,0.833,1631.3,19.5,10645258,NSE,National Stock Exchange of India,IN,False,True,False

In [9]:
# The Nasdaq screener is limited to the American market listings.
results = obb.equity.screener(country="india", provider="nasdaq").to_df()
display(len(results))
results.head(5).convert_dtypes()

9

,symbol,name,last_price,change,change_percent,market_cap
0,IBN,ICICI Bank Limited Common Stock,28.38,0.28,0.00996,99843513339
1,SIFY,Sify Technologies Limited American Depositary ...,0.3256,-0.0256,-0.07289,59693049
2,RDY,Dr. Reddy's Laboratories Ltd Common Stock,82.698,-1.512,-0.01796,13795536962
3,WIT,Wipro Limited Common Stock,6.16,-0.1,-0.01597,32186851595
4,HDB,HDFC Bank Limited Common Stock,59.805,-0.645,-0.01067,151444414047

### Search by Sector

In [11]:
sector_results = obb.equity.screener(
    country="IN", sector="financial_services", provider="fmp"
).to_df()
display(len(sector_results))
sector_results.head(5).convert_dtypes()

778

,symbol,name,market_cap,sector,industry,beta,price,last_annual_dividend,volume,exchange,exchange_name,country,is_etf,actively_trading,isFund
0,HDFCBANK.NS,HDFC Bank Limited,12426411437000,Financial Services,Banks - Regional,0.833,1631.3,19.5,10645258,NSE,National Stock Exchange of India,IN,False,True,False
1,ICICIBANK.NS,ICICI Bank Limited,8386856697000,Financial Services,Banks - Regional,0.862,1191.1,10.0,8563551,NSE,National Stock Exchange of India,IN,False,True,False
2,SBIN.NS,State Bank of India,7320857583000,Financial Services,Banks - Regional,0.888,820.3,13.7,7829674,NSE,National Stock Exchange of India,IN,False,True,False
3,SBIN.BO,State Bank of India,7319518891500,Financial Services,Banks - Regional,0.888,820.15,13.7,494896,BSE,Bombay Stock Exchange,IN,False,True,False
4,LICI.BO,Life Insurance Corporation of India,6803167418560,Financial Services,Insurance - Life,0.576,1075.6,13.0,29486,BSE,Bombay Stock Exchange,IN,False,True,False

In [12]:
# The same can be done with the Nasdaq provider, covering the American market.
sector_results = obb.equity.screener(
    sector="financial_services", provider="nasdaq"
).to_df()
display(len(sector_results))
sector_results.head(5).convert_dtypes()

1617

,symbol,name,last_price,change,change_percent,market_cap
0,CELZ,"Creative Medical Technology Holdings, Inc. Com...",3.5,0.3169,0.09956,4683441
1,STEC,Santech Holdings Limited American Depositary S...,0.48,0.043,0.0984,13440000
2,RILYG,"B. Riley Financial, Inc. 5.00% Senior Notes du...",12.0,1.03,0.09389,363543636
3,PFTA,Perception Capital Corp. III Class A Ordinary ...,11.75,0.98,0.09099,<NA>
4,ALFUW,Centurion Acquisition Corp. Warrant,0.1199,0.0099,0.09,<NA>

### Search by Industry

In [19]:
industry_results = obb.equity.screener(
    industry="apparel_manufacturing", provider="finviz"
).to_df()
display(len(industry_results))
industry_results.head(5)

25

,symbol,name,country,sector,industry,market_cap,price,change_percent,volume,price_to_earnings
0,XELB,Xcel Brands Inc,USA,Consumer Cyclical,Apparel Manufacturing,1.696000e+07,0.72,0.0460,2070,NaN
1,SGC,Superior Group of Companies Inc..,USA,Consumer Cyclical,Apparel Manufacturing,2.280000e+08,13.60,0.0049,39502,19.84
2,JRSH,Jerash holdings (US) Inc,USA,Consumer Cyclical,Apparel Manufacturing,3.626000e+07,2.95,0.0034,1348,NaN
3,PVH,PVH Corp,USA,Consumer Cyclical,Apparel Manufacturing,5.740000e+09,102.71,-0.0013,253106,9.09
4,RL,Ralph Lauren Corp,USA,Consumer Cyclical,Apparel Manufacturing,1.051000e+10,169.68,-0.0027,157365,16.36

In [18]:
industry_results = obb.equity.screener(
    industry="manufacturing", provider="fmp", country="IN"
).to_df()
display(len(industry_results))
industry_results.head(5)

297

,symbol,name,market_cap,sector,industry,beta,price,last_annual_dividend,volume,exchange,exchange_name,country,is_etf,actively_trading,isFund
0,TIMKEN.BO,Timken India Limited,2.787793e+11,Industrials,Manufacturing - Tools & Accessories,0.575,3706.25,2.5,5827,BSE,Bombay Stock Exchange,IN,False,True,False
1,TIMKEN.NS,Timken India Limited,2.787003e+11,Industrials,Manufacturing - Tools & Accessories,0.575,3705.20,2.5,115595,NSE,National Stock Exchange of India,IN,False,True,False
2,SKFINDIA.BO,SKF India Limited,2.615542e+11,Industrials,Manufacturing - Tools & Accessories,0.462,5290.55,130.0,1950,BSE,Bombay Stock Exchange,IN,False,True,False
3,SKFINDIA.NS,SKF India Limited,2.614405e+11,Industrials,Manufacturing - Tools & Accessories,0.462,5288.25,130.0,62289,NSE,National Stock Exchange of India,IN,False,True,False
4,PTCIL.NS,PTC Industries Limited,1.890617e+11,Industrials,Manufacturing - Metal Fabrication,0.510,13092.10,NaN,2965,NSE,National Stock Exchange of India,IN,False,True,False

### Search by Exchange

Some countries, like America, have multiple exchanges.  Narrow the search by combining two or more parameters.  The example below finds the companies listed on the American Stock Exchange (AMEX) that are domiciled in China.

In [21]:
exchange_results = obb.equity.screener(
    exchange="amex", country="CN", provider="fmp"
).to_df()
display(len(exchange_results))
exchange_results

5

,symbol,name,market_cap,sector,industry,beta,price,last_annual_dividend,volume,exchange,exchange_name,country,is_etf,actively_trading,isFund
0,MYND,"Mynd.ai, Inc.",93150152,Consumer Defensive,Education & Training Services,0.939,1.9200,5.628,10348,AMEX,American Stock Exchange,CN,False,True,False
1,AMBO,Ambow Education Holding Ltd.,3731855,Consumer Defensive,Education & Training Services,0.733,1.3065,NaN,21603,AMEX,American Stock Exchange,CN,False,True,False
2,CPHI,"China Pharma Holdings, Inc.",3664258,Healthcare,Drug Manufacturers - Specialty & Generic,0.726,0.2135,NaN,77994,AMEX,American Stock Exchange,CN,False,True,False
3,DXF,Dunxin Financial Holdings Limited,3243104,Financial Services,Financial - Credit Services,1.304,0.1394,NaN,187314,AMEX,American Stock Exchange,CN,False,True,False
4,ITP,"IT Tech Packaging, Inc.",2413803,Basic Materials,"Paper, Lumber & Forest Products",-0.120,0.2398,NaN,3062,AMEX,American Stock Exchange,CN,False,True,False

### Filter ADRs

Use the Nasdaq screener to get only American Depositary Receipts

In [22]:
obb.equity.screener(exsubcategory="adr", provider="nasdaq").to_df()

,symbol,name,last_price,change,change_percent,market_cap
0,GDS,GDS Holdings Limited ADS,16.1350,1.3750,0.09316,95038491
1,YQ,17 Education & Technology Group Inc. American ...,2.1700,0.1700,0.08500,7207460
2,STEC,Santech Holdings Limited American Depositary S...,0.4729,0.0359,0.08215,4125000
3,TURB,"Turbo Energy, S.A. American Depositary Shares",1.5342,0.1043,0.07294,1000000
4,FRES,Fresh2 Group Limited American Depositary Shares,1.7297,0.0997,0.06117,644183
...,...,...,...,...,...,...
190,JFU,9F Inc. American Depositary Shares,1.8000,NaN,NaN,3584421
191,XHG,XChange TEC.INC American Depositary Shares,0.9500,NaN,NaN,2780673
192,JZ,Jianzhi Education Technology Group Company Lim...,0.8000,NaN,NaN,1666667
193,NWGL,Nature Wood Group Limited American Depositary ...,1.6000,NaN,NaN,1493743
194,FORTY,Formula Systems (1985) Ltd. American Depositar...,76.0550,NaN,NaN,131939

### Filter by Metric

Applying some filters refines and targets the search. The example below finds listing on the NYSE domiciled in the USA, with a market cap between $100-300 billion, and exhibiting a beta value of less than 0.5

In [13]:
obb.equity.screener(
    exchange="nyse",
    mktcap_min=100000000000,
    mktcap_max=300000000000,
    country="us",
    beta_max=0.5,
    provider="fmp",
).to_df()

,symbol,name,market_cap,sector,industry,beta,price,last_annual_dividend,volume,exchange,exchange_name,country,is_etf,actively_trading,isFund
0,MRK,"Merck & Co., Inc.",294367485300,Healthcare,Drug Manufacturers - General,0.389000,116.130,3.08000,3111763,NYSE,New York Stock Exchange,US,False,True,False
1,VZ,Verizon Communications Inc.,171053845200,Communication Services,Telecommunications Services,0.393000,40.635,2.66000,6202285,NYSE,New York Stock Exchange,US,False,True,False
2,TBC,AT&T Inc. 5.625% Global Notes d,140078065351,Communication Services,Telecommunications Services,0.275703,24.565,1.40628,18782,NYSE,New York Stock Exchange,US,False,True,False
3,PGR,The Progressive Corporation,139775286220,Financial Services,Insurance - Property & Casualty,0.356000,238.660,0.40000,616656,NYSE,New York Stock Exchange,US,False,True,False
4,TBB,AT&T Inc. 5.35% GLB NTS 66,139658512827,Communication Services,Telecommunications Services,0.253859,23.395,1.33752,21852,NYSE,New York Stock Exchange,US,False,True,False
5,LMT,Lockheed Martin Corporation,132376882460,Industrials,Aerospace & Defense,0.454000,555.370,12.60000,304130,NYSE,New York Stock Exchange,US,False,True,False

### Finviz Screener

The `openbb-finviz` provider extension supports screener presets from V3 SDK and Terminal. See the details here: [https://pypi.org/project/openbb-finviz/](https://pypi.org/project/openbb-finviz/)

In [27]:
obb.equity.screener(
    metric="overview", signal="top_gainers", provider="finviz", mktcap="mid_over"
).to_df()

,symbol,name,country,sector,industry,market_cap,price,change_percent,volume,price_to_earnings
0,GRFS,Grifols SA ADR,Spain,Healthcare,Drug Manufacturers - General,2.270000e+09,8.81,0.1488,5055854,35.13
1,ZM,Zoom Video Communications Inc,USA,Technology,Software - Application,2.097000e+10,67.81,0.1258,15285228,24.27
2,EVH,Evolent Health Inc,USA,Healthcare,Health Information Services,3.680000e+09,31.61,0.1247,4519171,NaN
3,GDS,GDS Holdings Limited ADR,China,Technology,Information Technology Services,3.060000e+09,16.19,0.0968,2308546,NaN
4,LCID,Lucid Group Inc,USA,Consumer Cyclical,Auto Manufacturers,9.070000e+09,3.91,0.0922,41571321,NaN
5,OSIS,OSI Systems Inc.,USA,Technology,Electronic Components,2.690000e+09,157.68,0.0903,299756,21.68
6,ZK,ZEEKR Intelligent Technology Holding Ltd. ADR,China,Consumer Cyclical,Auto Manufacturers,4.450000e+09,17.99,0.0677,792117,NaN
7,QXO,QXO Inc.,USA,Technology,Software - Application,5.870000e+09,14.34,0.0614,4871978,NaN

## Get Available Indices

List all indices from a source with:

In [28]:
indices = obb.index.available(provider="yfinance").to_df()
print(len(indices))

indices[indices["name"].str.contains("ASX 200")]

274

,name,code,symbol
88,S&P/ASX 200 Index (AUD),au_asx200,^AXJO
90,S&P/ASX 200 Energy Sector Index (AUD),au_energy,^AXEJ
91,S&P/ASX 200 Resources Sector Index (AUD),au_resources,^AXJR
92,S&P/ASX 200 Materials Sector Index (AUD),au_materials,^AXMJ
94,S&P/ASX 200 Industrials Sector Index (AUD),au_industrials,^AXNJ
95,S&P/ASX 200 Consumer Discretionary Sector Inde...,au_discretionary,^AXDJ
96,S&P/ASX 200 Consumer Staples Sector Index (AUD),au_staples,^AXSJ
97,S&P/ASX 200 Health Care Sector Index (AUD),au_health,^AXHJ
98,S&P/ASX 200 Financials Sector Index (AUD),au_financials,^AXFJ
99,S&P/ASX 200 A-REIT Industry Index (AUD),au_reit,^AXPJ
100,S&P/ASX 200 Info Tech Sector Index (AUD),au_tech,^AXIJ
101,S&P/ASX 200 Communications Sector Index (AUD),au_communications,^AXTJ
102,S&P/ASX 200 Utilities Sector Index (AUD),au_utilities,^AXUJ

Filter the list down by querying the DataFrame.

With the `openbb-yfinance` extension, index time series can be  loaded using the ticker symbol or short code.  Non-American indices have a code beginning with the two-letter country code.

In [29]:
(
    obb.index.price.historical("au_utilities", provider="yfinance").to_df().tail(1)
    == obb.index.price.historical("^AXUJ", provider="yfinance").to_df().tail(1)
)

            open  high   low  close  volume
date
2024-08-22  True  True  True   True    True